#!/usr/bin/env bash

. ~/.local/lib/xlotus/xlfns

BIN=$XLOTUS_BIN

function fterm () { konsole --notransparency -p tabtitle="Floating" -e "$@"; }

case $1 in
    run) fterm $BIN/xl-run ;; 
    cmd) fterm $BIN/xl-cmd ;;
    *)
        ;;
esac
