#!/usr/bin/env bash

. "$HOME/.local/lib/xlotus/xlfns"

BIN="$XLOTUS_BIN"

float_konsole () { konsole --notransparency -p tabtitle="Floating" -e "$@"; }
float_foot () { footclient --app-id="floating" -e "$@"; }

case $1 in
    run) float_foot "$BIN"/xl-run ;; 
    cmd) float_foot "$BIN"/xl-cmd ;;
    yt) float_konsole "$BIN"/xl-yt -v ;;
    virt) float_foot "$BIN"/xl-virt ;;
    ff) float_foot "$BIN"/xl-ff ;;
    bmark)
        case $2 in
            add) float_foot "$BIN"/xl-mark -a ;;
            *) float_foot "$BIN"/xl-mark -g ;;
        esac
        ;;
    *)
        invalidArg "$1"
        ;;
esac
