#!/usr/bin/env bash

. "$HOME/.local/lib/xlotus/xlfns"

BIN="$XLOTUS_BIN"

fterm () { konsole --notransparency -p tabtitle="Floating" -e "$@"; }

case $1 in
    run) fterm "$BIN"/xl-run ;; 
    cmd) fterm "$BIN"/xl-cmd ;;
    yt) fterm "$BIN"/xl-yt -v ;;
    virt) fterm "$BIN"/xl-virt ;;
    ff) fterm "$BIN"/xl-ff ;;
    bmark)
        case $2 in
            add) fterm "$BIN"/xl-mark -a ;;
            *) fterm "$BIN"/xl-mark -g ;;
        esac
        ;;
    *)
        invalidArg "$1"
        ;;
esac
